#!/usr/bin/env php
<?php

define('ROOT', dirname(__FILE__));
define('APP_ROOT', ROOT . "/application");

if (!require_once(APP_ROOT . "/Boot.php")) {
    die ('BOOT ERROR');
}
$config = require(APP_ROOT . '/config/console.php');

\components\Core::$app = new \components\Console($config);
\components\Core::$app->run();